.pragma library

// Zone list from https://www.e-solat.gov.my
var zones = [
    { code: "JHR01", state: "Johor", name: "Pulau Aur dan Pulau Pemanggil" },
    { code: "JHR02", state: "Johor", name: "Johor Bahru, Kota Tinggi, Mersing, Kulai" },
    { code: "JHR03", state: "Johor", name: "Kluang, Pontian" },
    { code: "JHR04", state: "Johor", name: "Batu Pahat, Muar, Segamat, Gemas Johor, Tangkak" },
    { code: "KDH01", state: "Kedah", name: "Kota Setar, Kubang Pasu, Pokok Sena (Daerah Kecil)" },
    { code: "KDH02", state: "Kedah", name: "Kuala Muda, Yan, Pendang" },
    { code: "KDH03", state: "Kedah", name: "Padang Terap, Sik" },
    { code: "KDH04", state: "Kedah", name: "Baling" },
    { code: "KDH05", state: "Kedah", name: "Bandar Baharu, Kulim" },
    { code: "KDH06", state: "Kedah", name: "Langkawi" },
    { code: "KDH07", state: "Kedah", name: "Puncak Gunung Jerai" },
    { code: "KTN01", state: "Kelantan", name: "Bachok, Kota Bharu, Machang, Pasir Mas, Pasir Puteh, Tanah Merah, Tumpat, Kuala Krai, Mukim Chiku" },
    { code: "KTN02", state: "Kelantan", name: "Gua Musang (Daerah Galas Dan Bertam), Jeli, Jajahan Kecil Lojing" },
    { code: "MLK01", state: "Melaka", name: "SELURUH NEGERI MELAKA" },
    { code: "NGS01", state: "Negeri Sembilan", name: "Tampin, Jempol" },
    { code: "NGS02", state: "Negeri Sembilan", name: "Jelebu, Kuala Pilah, Rembau" },
    { code: "NGS03", state: "Negeri Sembilan", name: "Port Dickson, Seremban" },
    { code: "PHG01", state: "Pahang", name: "Pulau Tioman" },
    { code: "PHG02", state: "Pahang", name: "Kuantan, Pekan, Muadzam Shah" },
    { code: "PHG03", state: "Pahang", name: "Jerantut, Temerloh, Maran, Bera, Chenor, Jengka" },
    { code: "PHG04", state: "Pahang", name: "Bentong, Lipis, Raub" },
    { code: "PHG05", state: "Pahang", name: "Genting Sempah, Janda Baik, Bukit Tinggi" },
    { code: "PHG06", state: "Pahang", name: "Cameron Highlands, Genting Higlands, Bukit Fraser" },
    { code: "PHG07", state: "Pahang", name: "Daerah Rompin, (Mukim Rompin, Mukim Endau, Mukim Pontian)" },
    { code: "PLS01", state: "Perlis", name: "Kangar, Padang Besar, Arau" },
    { code: "PNG01", state: "Pulau Pinang", name: "Seluruh Negeri Pulau Pinang" },
    { code: "PRK01", state: "Perak", name: "Tapah, Slim River, Tanjung Malim" },
    { code: "PRK02", state: "Perak", name: "Kuala Kangsar, Sg. Siput, Ipoh, Batu Gajah, Kampar" },
    { code: "PRK03", state: "Perak", name: "Lenggong, Pengkalan Hulu, Grik" },
    { code: "PRK04", state: "Perak", name: "Temengor, Belum" },
    { code: "PRK05", state: "Perak", name: "Kg Gajah, Teluk Intan, Bagan Datuk, Seri Iskandar, Beruas, Parit, Lumut, Sitiawan, Pulau Pangkor" },
    { code: "PRK06", state: "Perak", name: "Selama, Taiping, Bagan Serai, Parit Buntar" },
    { code: "PRK07", state: "Perak", name: "Bukit Larut" },
    { code: "SBH01", state: "Sabah", name: "Bahagian Sandakan (Timur), Bukit Garam, Semawang, Temanggong, Tambisan, Bandar Sandakan, Sukau" },
    { code: "SBH02", state: "Sabah", name: "Beluran, Telupid, Pinangah, Terusan, Kuamut, Bahagian Sandakan (Barat)" },
    { code: "SBH03", state: "Sabah", name: "Lahad Datu, Silabukan, Kunak, Sahabat, Semporna, Tungku, Bahagian Tawau (Timur)" },
    { code: "SBH04", state: "Sabah", name: "Bandar Tawau, Balong, Merotai, Kalabakan, Bahagian Tawau (Barat)" },
    { code: "SBH05", state: "Sabah", name: "Kudat, Kota Marudu, Pitas, Pulau Banggi, Bahagian Kudat" },
    { code: "SBH06", state: "Sabah", name: "Gunung Kinabalu" },
    { code: "SBH07", state: "Sabah", name: "Kota Kinabalu, Ranau, Kota Belud, Tuaran, Penampang, Papar, Putatan, Bahagian Pantai Barat" },
    { code: "SBH08", state: "Sabah", name: "Pensiangan, Keningau, Tambunan, Nabawan, Bahagian Pendalaman (Atas)" },
    { code: "SBH09", state: "Sabah", name: "Beaufort, Kuala Penyu, Sipitang, Tenom, Long Pasia, Membakut, Weston, Bahagian Pendalaman (Bawah)" },
    { code: "SGR01", state: "Selangor", name: "Gombak, Petaling, Sepang, Hulu Langat, Hulu Selangor, S.Alam" },
    { code: "SGR02", state: "Selangor", name: "Kuala Selangor, Sabak Bernam" },
    { code: "SGR03", state: "Selangor", name: "Klang, Kuala Langat" },
    { code: "SWK01", state: "Sarawak", name: "Limbang, Lawas, Sundar, Trusan" },
    { code: "SWK02", state: "Sarawak", name: "Miri, Niah, Bekenu, Sibuti, Marudi" },
    { code: "SWK03", state: "Sarawak", name: "Pandan, Belaga, Suai, Tatau, Sebauh, Bintulu" },
    { code: "SWK04", state: "Sarawak", name: "Sibu, Mukah, Dalat, Song, Igan, Oya, Balingian, Kanowit, Kapit" },
    { code: "SWK05", state: "Sarawak", name: "Sarikei, Matu, Julau, Rajang, Daro, Bintangor, Belawai" },
    { code: "SWK06", state: "Sarawak", name: "Lubok Antu, Sri Aman, Roban, Debak, Kabong, Lingga, Engkelili, Betong, Spaoh, Pusa, Saratok" },
    { code: "SWK07", state: "Sarawak", name: "Serian, Simunjan, Samarahan, Sebuyau, Meludam" },
    { code: "SWK08", state: "Sarawak", name: "Kuching, Bau, Lundu, Sematan" },
    { code: "SWK09", state: "Sarawak", name: "Zon Khas (Kampung Patarikan)" },
    { code: "TRG01", state: "Terengganu", name: "Kuala Terengganu, Marang, Kuala Nerus" },
    { code: "TRG02", state: "Terengganu", name: "Besut, Setiu" },
    { code: "TRG03", state: "Terengganu", name: "Hulu Terengganu" },
    { code: "TRG04", state: "Terengganu", name: "Dungun, Kemaman" },
    { code: "WLY01", state: "Wilayah Persekutuan", name: "Kuala Lumpur, Putrajaya" },
    { code: "WLY02", state: "Wilayah Persekutuan", name: "Labuan" },
];

function find(code) {
    for (var i = 0; i < zones.length; i++) {
        if (zones[i].code === code) return zones[i];
    }
    return null;
}
